# Generated by Django 4.0.4 on 2022-05-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('main_body', models.CharField(max_length=500, verbose_name='正文')),
                ('writer', models.CharField(max_length=10, verbose_name='作者')),
                ('edited_time', models.CharField(max_length=32, verbose_name='编辑时间')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户注册')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
    ]
