# Generated by Django 4.0.4 on 2022-06-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_banner_category_link_tag_tui_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='essay',
        ),
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
